### DISCUSSION TITLE
Does this specification allows for one to specify the upstream system source for the data or just the delivery server?

### DISCUSSION THREAD

**Discussion by taksqth** [datamesh-architecture/datacontract-specification#106] [General]
Not sure if I missed it in the specification, but it is common to have an upstream system such as MongoDB and the deliver contract referring to a middle layer such as S3. From what I understood, `server` refers to the later, but it is useful to have more information regarding the true upstream original source. How would I, if it is possible, annotate this in the current schema?

**Comment by jochenchrist** [comment]
You can use the `lineage` field for upstream information: https://datacontract.com/#lineage-object

Example:

```
models:
  orders:
    fields:
      order_id:
        type: string
        lineage:
          inputFields:
            - namespace: my-mongodb
              name: checkout_db.orders
              field: order_id
              transformations:
                - type: DIRECT
                  subtype: IDENTITY
                  description: The order ID from the checkout order
            - namespace: my-mongodb
              name: checkout_db.orders
              field: order_timestamp
                - type: INDIRECT
                  subtype: SORT
      customer_email_address_hash:
        type: string
        lineage:
          inputFields:
            - namespace: my-mongodb
              name: checkout_db.orders
              field: email_address
              transformations:
                - type: DIRECT
                  subtype: Transformation
                  description: The email address from the checkout order, hashed with SHA-256
                  masking: true

```

Hope this helps.
