### ISSUE TITLE
Lineage

### ISSUE THREAD

**Issue by jochenchrist** [datamesh-architecture/datacontract-specification#90]
Support for field-level upstream lineage could be aligned to OpenLinage format for "inputFields" (https://openlineage.io/docs/spec/facets/dataset-facets/column_lineage_facet/)

First draft, open to discuss:

```
fields:
  order_id:
    type: string
    lineage: # new property
      inputFields:
        - namespace: food_delivery
          name: public.delivery_7_days
          field: order_id
          transformations:
            - type: DIRECT
              subtype: IDENTITY
              description: ""
              masking: false
        - namespace: food_delivery
          name: public.delivery_7_days
          field: order_placed_on
          transformations:
            - type: INDIRECT
              subtype: SORT
              description: ""
              masking: false
        - namespace: food_delivery
          name: public.delivery_7_days
          field: order_delivered_on
          transformations:
            - type: INDIRECT
              subtype: SORT
              description: ""
              masking: false
```
